# Use the official Playwright Docker image
FROM mcr.microsoft.com/playwright:v1.44.0-focal

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json .
RUN npm install

# Copy the rest of the project files
COPY . .

# Run tests
CMD ["npm", "test"]